services:
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://db:27017/app-bancas
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    container_name: app-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: